Peopletracker: PeopleTracker.src.maskrcnn Namespace Reference
PeopleTracker.src.maskrcnn Namespace Reference
Functions
load_predicted (pred_file)
display_preds (frame, frame_num, pred_dict, ratios)
predict (filename, model="mask_rcnn_coco_person.h5", class_names=["BG", "person"], step=10, display=False, progress=None, logger=None)
compute_iou (box, boxes, boxes_area, ratios=(1, 1), frame=None)
track_predictions (pred_dict, video, method=0, id_prefix="P", KalmanFilter=KalmanPred(), ratios=(1, 1), buffer=10, preview=True)
Variables
int NEAREST_CENTROID = 0
int NEAREST_CORNERS = 1
int NEAREST_BOX = 2
int NEAREST_KALMAN_CENTROID = 3
int NEAREST_KALMAN_CORNERS = 4
int NEAREST_KALMAN = 5
display
True
step
pred_dict = load_predicted("K:/Github/PeopleTracker/videos/(Simple) GP014125_predict.csv")
Detailed Description
Model from: https://github.com/Superlee506/Mask_RCNN_Humanpose
Cuda Version 10.1
CUDNN Version
                         # tensorflow==2.4.0 (Could be wrong??? just use GPU)d
Tensorflow version 2.3.0 # tensorflow-gpu==2.3.0
Function Documentation
compute_iou()
compute_iou (box, boxes, boxes_area, ratios = (1,1), frame = None)
Calculates IoU of the given box with the array of the given boxes.
box: 1D vector [x1, y1, x2, y2]
boxes: [boxes_count, (x1, y1, x2, y2)]
box_area: float. the area of 'box'
boxes_area: array of length boxes_count.
ratio: ratio (width, height) to scale boxes from video resolution to analysis resolution
Note: the areas are passed in rather than calculated here for
efficiency. Calculate once in the caller to avoid duplicate work.
def compute_iou(box, boxes, boxes_area, ratios=(1,1), frame=None):
    """Calculates IoU of the given box with the array of the given boxes.
    box: 1D vector [x1, y1, x2, y2]
    boxes: [boxes_count, (x1, y1, x2, y2)]
    box_area: float. the area of 'box'
    boxes_area: array of length boxes_count.
    ratio: ratio (width, height) to scale boxes from video resolution to analysis resolution
    Note: the areas are passed in rather than calculated here for
    efficiency. Calculate once in the caller to avoid duplicate work.
    """
    area = (box[0] - box[2]) * (box[1] - box[3]) # SOMETHING IS WRONG WITH BOX. GOOD NIGHT!
    ious = []
    for index, preds in enumerate(boxes):
        x1 = int(preds[0]*ratios[0])
        y1 = int(preds[1]*ratios[1])
        x2 = int(preds[2]*ratios[0])
        y2 = int(preds[3]*ratios[1])
        if frame is not None:
            cv2.rectangle(frame, (x1,y1), (x2,y2), (150,150,0), 1)
        xA = max(box[0], x1)
        yA = max(box[1], y1)
        xB = min(box[2], x2)
        yB = min(box[3], y2)
        interArea = max(0, xB - xA + 1) * max(0, yB - yA + 1)
        boxBArea = (x2 - x1 + 1) * (y2 - y1 + 1)
        # print(box_area, boxBArea)
        iou = interArea / float(area + boxBArea - interArea)
        ious.append(iou)
    return ious, frame
References PeopleTracker.src.maskrcnn.load_predicted(), and PeopleTracker.src.maskrcnn.predict().
display_preds()
display_preds (frame, frame_num, pred_dict, ratios)
Displays the prediction
def display_preds(frame, frame_num, pred_dict, ratios):
    """
    Displays the prediction
    """
    if frame_num in pred_dict.keys():
        boxes = pred_dict[frame_num][0]
        # print("RATIOS", ratios)
        for box in boxes:
            if box:
                x1 = box[0]
                y1 = box[1]
                x2 = box[2]
                y2 = box[3]
                p1 = (int(x1*ratios[0]), int(y1*ratios[1]))
                p2 = (int(x2*ratios[0]), int(y2*ratios[1]))
                # print(p1,p2)
                frame = cv2.rectangle(frame, p1, p2, (0, 255, 0), 1)
                frame = cv2.putText(frame,(str(int(x1*ratios[0]))) + "," + str(int(y1*ratios[1])) , p1, 5, 0.5, (0,0,0))
    return frame
load_predicted()
load_predicted (pred_file)
Loads predicted data into a variable for later use.
Pred_dict[frame_number] = Lost of boxes
A box is described by:
x = box[0],
y = box[1],
width = box[2],
height = box[3]
def load_predicted(pred_file):
    """
    Loads predicted data into a variable for later use.
    Pred_dict[frame_number] = Lost of boxes
    A box is described by:
    x = box[0],
    y = box[1],
    width = box[2],
    height = box[3]
    """
    preds = pd.read_csv(pred_file)
    # print(preds)
    frames = preds.iloc[:,0].tolist()
    rois = preds.iloc[:,1].tolist()
    pred_dict = {}
    for i, roi in enumerate(rois):
        roi_list = roi.split("\n")
        box_list = []
        box_areas = []
        #Parse the string saved in csv into a list
        for box in roi_list:
            box = box.replace("[", "")
            box = box.replace("]", "")
            box = box.split()
            box = tuple(map(int, box))
            area = 0
            if box:
                y1 = box[0]
                x1 = box[1]
                y2 = box[2]
                x2 = box[3]
                box = (x1,y1,x2,y2)
                area = (box[0] - box[2]) * (box[1] - box[3])
            box_areas.append(area)
            box_list.append(box)
        pred_dict[frames[i]] = (box_list, box_areas)
    return pred_dict
Referenced by PeopleTracker.src.maskrcnn.compute_iou().
predict()
predict (filename, model = "mask_rcnn_coco_person.h5", class_names = ["BG", "person"], step = 10, display = False, progress = None, logger = None)
Uses MaskRCNN COCO models and uses them to predict items on the image.
Steps indicate how frequently the model should predict on the video (default every 10 frames)
Display shows predictions visually
Progress is a QProgressDialog for the application
Logger is a logger which both displays info and records it for crashlogger
Exports results into filename_predict.csv
def predict(filename, model="mask_rcnn_coco_person.h5", class_names=["BG", "person"], step=10, display=False, progress=None, logger=None):
    '''
    Uses MaskRCNN COCO models and uses them to predict items on the image.
    Steps indicate how frequently the model should predict on the video (default every 10 frames)
    Display shows predictions visually
    Progress is a QProgressDialog for the application
    Logger is a logger which both displays info and records it for crashlogger
    Exports results into filename_predict.csv
    '''
    from pixellib.instance import custom_segmentation
    import tensorflow as tf
    print("Using Tensorflow: ", tf. __version__)
    gpus = tf.config.experimental.list_physical_devices('GPU')
    if gpus:
        try:
            for gpu in gpus:
                tf.config.experimental.set_memory_growth(gpu, True)
        except RuntimeError as e:
            print(e)
    class_name = model.split('_')[-1] #CLASSNAME.h5
    class_name = class_name.split('.')[0] #CLASSNAME
    class_names = ["BG", class_name]
    print(class_name)
    #loads models
    custom_model = custom_segmentation()
    custom_model.inferConfig(num_classes= 1, class_names=class_names)
    custom_model.load_model(model)
    #loads videos
    cap = cv2.VideoCapture(filename)
    vid_length = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    #init lists for temp storage
    roi_list = []
    frame_list = []
    score_list = []
    time_queue = []
    fps_list = []
    print(vid_length)
    #iterate through the video by said steps
    for frame_num in range(0, vid_length, step):
        start = timeit.default_timer()
        #set frame number to i
        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_num)
        ret, frame = cap.read()
        if ret:
            if progress == True:
                print("Progress:" + str(frame_num/vid_length), end="\r")
            elif progress is not None:
                if progress.wasCanceled():
                    return None, None, None
                if frame_num == 0:
                    progress.setLabelText("Predict people location progress")
                    progress.setRange(0,vid_length)
                progress.setValue(frame_num)
                QtCore.QCoreApplication.processEvents()
            #Segment the image
            segmask, frame = custom_model.segmentFrame(frame, True)
            # train_dataset_keypoints = coco.CocoDataset(task_type="person_keypoints")
            #Place data in lists for easy export
            roi_list.append(segmask['rois'])
            score_list.append(segmask['scores'])
            # print(segmask['person_keypoints'])
            frame_list.append(frame_num)
            if display:
                cv2.imshow("Predictions", frame)
                key = cv2.waitKey(1) & 0xFF
            stop = timeit.default_timer()
            if len(time_queue) == 60:
                time_queue.pop()
            fps = 1/(stop - start)
            fps_list.append(fps)
            time_queue.append(fps)
            print('FPS:', fps)
            fps = sum(time_queue) / len(time_queue)
            if logger is not None:
                eta = ((vid_length-frame_num)/(step*fps))
                printstr = "Predicting frame " + str(frame_num) + "/" + str(vid_length) + " \npeople: "+ str(len(segmask['rois'])) + " \nETA: " + time.strftime('%H:%M:%S', time.gmtime(eta))
                logger(printstr)
                progress.setLabelText("Predict people location progress \n\n" + printstr)
                if frame_num + step == vid_length:
                    logger("Predicting Complete.")
            else:
                print("Predicting frame " + str(frame_num) + "/" + str(vid_length) + " people:"+ str(len(segmask['rois'])))
                eta = ((vid_length-frame_num)/(step*fps))
                print("ETA:", time.strftime('%H:%M:%S', time.gmtime(eta)))
    end_time = time.time()
    #create dataframe
    data = {
        "Frame_Num":frame_list,
        "Region_of_interest":roi_list,
        "Scores":score_list,
        "Predict_Duration":fps_list
    }
    #export dataframe
    df = pd.DataFrame(data)
    export_csv = df.to_csv((filename[:-4] + "_predict.csv"), index = None, header=True) #Don't forget to add '.csv' at the end of the path
    return frame_list, roi_list, score_list
Referenced by PeopleTracker.src.maskrcnn.compute_iou().
track_predictions()
track_predictions (pred_dict, video, method = 0, id_prefix = "P", KalmanFilter = KalmanPred(), ratios = (1,1), buffer = 10, preview = True)
def track_predictions(pred_dict, video, method = 0, id_prefix="P", KalmanFilter=KalmanPred(), ratios=(1,1), buffer=10, preview=True):
    # pred_track_dict = {}
    Frames = []
    Name = []
    Id = []
    Pixel_Loc_x = []
    Pixel_Loc_y = []
    BBox_TopLeft_x = []
    BBox_TopLeft_y = []
    BBox_BottomRight_x = []
    BBox_BottomRight_y = []
    FrameRate = []
    Max_Pixel_X = []
    Max_Pixel_Y = []
    ct = CentroidTracker(buffer)
    # ct = NewCentroidTracker(buffer, KalmanFilter)
    cap = cv2.VideoCapture(video)
    cv2.startWindowThread()
    export = video[:-3]
    vid_length = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    for frame_num in pred_dict.keys():
        # print(frame_num)
        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_num)
        ret, frame = cap.read()
        boxes = pred_dict[frame_num][0]
        # show the frame and don't do anything if there are no predictions
        if boxes == [()]:
            cv2.imshow("IDs", frame)
            key = cv2.waitKey(1)
            if key == ord('q'):
                print("QUITTING")
                cv2.destroyWindow("IDs")
                break
            continue
        # rects = []
        # loop over the detections
        # for i in range(0, boxes.shape[2]):
            # filter out weak detections by ensuring the predicted
            # probability is greater than a minimum threshold
            # if boxes[0, 0, i, 2] > args["confidence"]:
            #     # compute the (x, y)-coordinates of the bounding box for
            #     # the object, then update the bounding box rectangles list
            #     box = boxes[0, 0, i, 3:7] * np.array([W, H, W, H])
            #     rects.append(box.astype("int"))
            #     # draw a bounding box surrounding the object so we can
            #     # visualize it
            #     (startX, startY, endX, endY) = box.astype("int")
            #     cv2.rectangle(frame, (startX, startY), (endX, endY),
            #         (0, 255, 0), 2)
        # update our centroid tracker using the computed set of bounding
        # box rectangles
        objects = ct.update(boxes)
        # print(objects)
        # track_object = boxe
        # if preview:
        # index = 0
        # print("BOXES LENGTH", boxes, len(boxes))
        # loop over the tracked objects
        # print(len(objects))
        for ObjectId in objects.keys():
            data = objects[ObjectId]
            centroid = data[0]
            box = data[1]
            x1 = int(box[0]*ratios[0])
            y1 = int(box[1]*ratios[1])
            x2 = int(box[2]*ratios[0])
            y2 = int(box[3]*ratios[1])
            # draw both the ID of the object and the centroid of the
            Frames.append(frame_num)
            Name.append(ObjectId)
            Id.append(ObjectId)
            Pixel_Loc_x.append(centroid[0])
            Pixel_Loc_y.append(centroid[1])
            BBox_TopLeft_x.append(x1)
            BBox_TopLeft_y.append(cap.get(cv2.CAP_PROP_FRAME_HEIGHT) - y1)
            BBox_BottomRight_x.append(x2)
            BBox_BottomRight_y.append(cap.get(cv2.CAP_PROP_FRAME_HEIGHT) - y2)
            FrameRate.append(cap.get(cv2.CAP_PROP_FPS))
            Max_Pixel_X.append(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
            Max_Pixel_Y.append(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
            if preview:
                # object on the output frame
                text = "ID {}".format(ObjectId)
                cv2.putText(frame, text, (centroid[0] - 10, centroid[1] - 10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
                cv2.circle(frame, (centroid[0], centroid[1]), 4, (0, 255, 0), -1)
                cv2.rectangle(frame, (x1,y1), (x2,y2), (150,150,0), 1)
        cv2.imshow("IDs", frame)
        key = cv2.waitKey(1)
        if key == ord('q'):
            print("QUITTING")
            cv2.destroyWindow("IDs")
            break
        predicted_ids = {"Frame_Num": Frames, "Name":Name, "ID":Id, "Pixel_Loc_x":Pixel_Loc_x, "Pixel_Loc_y":Pixel_Loc_y,
                        "BBox_TopLeft_x":BBox_TopLeft_x, "BBox_TopLeft_y":BBox_TopLeft_y,
                        "BBox_BottomRight_x":BBox_BottomRight_x,"BBox_BottomRight_y":BBox_BottomRight_y,
                        "FrameRate":FrameRate, "Max_Pixel_x":Max_Pixel_X, "Max_Pixel_y":Max_Pixel_Y
        }
        output_dict = pd.DataFrame(predicted_ids)
    return output_dict