Peopletracker: FPS
FPS
Public Member Functions
__init__ (self)
start (self)
stop (self)
update (self)
elapsed (self)
fps (self)
Protected Attributes
_start
_end
_numFrames
Constructor & Destructor Documentation
__init__()
__init__ (self)
    def __init__(self):
        # store the start time, end time, and total number of frames
        # that were examined between the start and end intervals
        self._start = None
        self._end = None
        self._numFrames = 0
Member Function Documentation
elapsed()
elapsed (self)
    def elapsed(self):
        # return the total number of seconds between the start and
        # end interval
        return (self._end - self._start).total_seconds()
fps()
fps (self)
    def fps(self):
        # compute the (approximate) frames per second
        return self._numFrames / self.elapsed()
Referenced by tracker_evaluation.__init__(), tracker_evaluation.load_json(), and tracker_evaluation.load_tracker_data().
start()
start (self)
    def start(self):
        # start the timer
        self._start = datetime.datetime.now()
        return self
stop()
stop (self)
    def stop(self):
        # stop the timer
        self._end = datetime.datetime.now()
update()
update (self)
    def update(self):
        # increment the total number of frames examined during the
        # start and end intervals
        self._numFrames += 1
The documentation for this class was generated from the following file:
K:/Github/PeopleTracker/src/fps.py