Peopletracker: CameraPosition
CameraPosition
Public Member Functions
__init__ (self, source_vid=None, reference_vid=None)
openFileNameDialog (self)
initUI (self)
init_menubar (self)
set_view_roomestimation (self)
processtrigger (self, trigger)
stitch (self, image_list, out_path=None)
set_source (self, video_path, frame=0)
add_reference (self, video_path, frame_start, total_frames, step)
find_reference (self, query_img, train_img)
find_features (self, img1, img2)
match_features (self, des1, des2, mode=0)
find_homography (self, img1, img2, kp1, kp2, matches)
show_estimation (self)
collect_frames (self, video_source, start_frame, skip, total_frames)
Public Attributes
title
left
top
width
height
stitched_img
reference_imgs
room_estimation
source_img
stitch_list
layout
processtrigger
room_widget
room_layout
bottom_left_pt_x
bottom_left_pt_y
top_left_pt_x
top_left_pt_y
top_right_pt_x
top_right_pt_y
bottom_right_pt_x
bottom_right_pt_y
Detailed Description
Steps to stitching the images
1) Find Keypoints between images (SIFT/SURF/ORB?)
 - SIFT and SURF are patented and if you want to use it in a real-world application, you need to pay a licensing fee.
 - ORB is not.
2) Compute the distances between every descriptor
3) Select the best matches to align (Knn - 2 best matches for each descriptor {k=2})
- finds two best matches for each feature and leaves the best one only if the ratio between descriptor distances is greater than the threshold
4) Estimate Homography (Homography Estimator)
5) Warp the images (translate and rotate) to align
    - NOTE this is where we will extract the top left of each frame for reference on the stitched image
    locations of each frame (hopefully)
6) Stitch the images (Stitch and blend)
Member Function Documentation
collect_frames()
collect_frames (self, video_source, start_frame, skip, total_frames)
Collects the images for stitching
Referenced by room_estimation.save_room(), room_estimation.stitch_rooms(), and room_estimation.stitch_trackers().
find_features()
find_features (self, img1, img2)
This function finds features between 2 images using ORB
Desribes keypoints using "steer" BRIEF
References CameraPosition.find_reference(), CameraPosition.reference_imgs, CameraPosition.source_img, and CameraPosition.stitched_img.
The documentation for this class was generated from the following file:
K:/Github/PeopleTracker/src/camera_position.py