Peopletracker: DataLogger
DataLogger
Public Member Functions
__init__ (self, video, video_location=None, video_metadata=None, intervention_level=NO_INTVERVENTION_TRACKER, ground_truth_folder=None)
start_recording (self)
User input logging starts here #.
end_recording (self)
ends recording timer
start_timer (self, timer_id)
get_time_elapsed (self, timer_id)
end_timer (self, timer_id)
adjustment (self, frame_number, from_box, timer_id, tracker_id, intervention_type="USER", to_box=None)
end_adjustment (self, to_box, timer_id)
paused (self, frame_number, pause_type, timer_id, tracker_id)
end_pause (self)
slider_moved (self, frame_from, timer_id, tracker_id)
end_slider (self, frame_to, timer_id)
record_errors (self, frame)
get_tracker_score (self)
get_video_characteristics (self, video=None)
VIDEO COMPLEXITY STARTS HERE #.
illumination (self, frame)
optical_flow (self, frame)
optical_flow_pan (self, flow, dominance_threshold=0.4, magnitude_threshold=0.5)
optical_flow_zoom (self, flow, dominance_threshold=0.7, magnitude_threshold=1)
ground_truth_characteristics (self, frame_num)
objects_occluded (self, folder_path, fps)
check_intervention_level (self)
export_charactoristics (self, file_path)
export_activity (self, file_path)
plot_chars_df (self)
occuding_objects (self, occluding_tracks_csv, occluding_threshold=0.8)
Public Attributes
intervention_level
String representing constants.
ground_truth_folder
te
metadata
video
video_id
video_location
start_time_id
previous_frame
logging_dict
timer_dict
paused_data
slider_data
adjust_data
logger_df
video_info_df
Member Function Documentation
adjustment()
adjustment (self, frame_number, from_box, timer_id, tracker_id, intervention_type = "USER", to_box = None)
Records the frame number and locations where the tracker is moved from and to.
Records what made the adjustment.
    Human - If the user made the adjustment
    Model - If the MaskRCNN model made the automatic adjustment
References DataLogger.adjust_data, DataLogger.end_adjustment(), DataLogger.intervention_level, and DataLogger.start_timer().
end_adjustment()
end_adjustment (self, to_box, timer_id)
Records the adjustment when final changes are made. This contributes final location and duration.
References DataLogger.adjust_data, DataLogger.get_time_elapsed(), and DataLogger.logger_df.
Referenced by DataLogger.adjustment().
end_pause()
end_pause (self)
After paused() is called, end_pause is used to end the paused action and add the duration to the logger.
References DataLogger.end_timer(), DataLogger.get_time_elapsed(), DataLogger.logger_df, DataLogger.paused_data, and DataLogger.start_time_id.
end_recording()
end_recording (self)
ends recording timer
Ends recording by setting the second value in the tuple (start, end) to the current time.
References DataLogger.start_time_id, and DataLogger.timer_dict.
end_slider()
end_slider (self, frame_to, timer_id)
When slider_moved() is called, we call end_slider which removes a duration timer and adds the duration and SLIDER action to the logger.
References DataLogger.end_timer(), DataLogger.get_time_elapsed(), DataLogger.logger_df, DataLogger.slider_data, and DataLogger.timer_dict.
end_timer()
end_timer (self, timer_id)
Ends the timer from when the project is finished
References DataLogger.get_time_elapsed(), and DataLogger.timer_dict.
Referenced by DataLogger.end_pause(), and DataLogger.end_slider().
get_time_elapsed()
get_time_elapsed (self, timer_id)
returns elapsed time of a timer in seconds
References DataLogger.start_time_id, and DataLogger.timer_dict.
Referenced by DataLogger.end_adjustment(), DataLogger.end_pause(), DataLogger.end_slider(), and DataLogger.end_timer().
get_tracker_score()
get_tracker_score (self)
Not implemented
get_video_characteristics()
get_video_characteristics (self, video = None)
VIDEO COMPLEXITY STARTS HERE #.
Records all video characteristics.
    This will be done independently from the user input
    and will be constants between intervention types
References DataLogger.ground_truth_characteristics(), DataLogger.illumination(), DataLogger.optical_flow(), DataLogger.te, DataLogger.video, DataLogger.video_id, DataLogger.video_info_df, and DataLogger.video_location.
ground_truth_characteristics()
ground_truth_characteristics (self, frame_num)
Records ground truth height, width, and distance from last frame
References DataLogger.te.
Referenced by DataLogger.get_video_characteristics().
illumination()
illumination (self, frame)
Records the average intensity of the RGB image in greyscale with values between 0 (black) and 255 (white)
Intensity = (R + G + B)/3
Referenced by DataLogger.get_video_characteristics().
objects_occluded()
objects_occluded (self, folder_path, fps)
Records weather the occlusion flag has occured on that frame. Records how many IDs have been occluded.
References DataLogger.check_intervention_level(), DataLogger.intervention_level, DataLogger.logger_df, DataLogger.te, and DataLogger.video_info_df.
occuding_objects()
occuding_objects (self, occluding_tracks_csv, occluding_threshold = 0.8)
Given recorded occluding objects, check the precision of ground truth onto occluding object.
If precision of ground truth is above threshold, this means that object is occluded.
This is the same measure as check_occlusion but data in this context is different and
therefore a different function
optical_flow()
optical_flow (self, frame)
Uses optical flow to measure the average magnitude of movement from the flow of pixels.
Also records the resolution of the image
Returns values in a dictionary with names:
    Mean
    Median
    STD
    Mean_Magnitude
    Dominant_Zoom
    Percent_Zoom
    Zoom_Dominance_Thresh
    Zoom_Magnitude_Thresh
    Dominant_Pan
    Percent_Pan
    Pan_Dominance_Thresh
    Pan_Magnitude_Thresh
[66] Gunnar Farnebäck. Two-frame motion estimation based on polynomial expansion. In Image Analysis, pages 363–370. Springer, 2003.
References DataLogger.optical_flow_pan(), DataLogger.optical_flow_zoom(), and DataLogger.previous_frame.
Referenced by DataLogger.get_video_characteristics().
optical_flow_pan()
optical_flow_pan (self, flow, dominance_threshold = 0.4, magnitude_threshold = 0.5)
Vector orientation:
t+1=current frame, t=previous frame
atan(
    (yi^(t+1) - yi^(t)) /
    (xi^(t+1) - xi^(t))
)
Calculate Dominant Orientation = Peak value in orientation histogram of the imag
np.histogram(np.array(vector orientation))
returns the dominant orientation given a threshold, the threshold it passed by, and the average magnitude of movement.
Makkapati, V. (2008). Robust camera pan and zoom change detection using optical flow.
In National conference on computer vision, pattern recognition,
image processing and graphics (pp. 73-78).
Referenced by DataLogger.optical_flow().
optical_flow_zoom()
optical_flow_zoom (self, flow, dominance_threshold = 0.7, magnitude_threshold = 1)
Describe each vector's direction.
Returns
    0 if diverging (zoom in), 1 if converging (zoom out), otherwise none.
    percent of dominance
    domenance threshold
    mean magnitude threshold
Makkapati, V. (2008). Robust camera pan and zoom change detection using optical flow.
In National conference on computer vision, pattern recognition,
image processing and graphics (pp. 73-78).
Referenced by DataLogger.optical_flow().
paused()
paused (self, frame_number, pause_type, timer_id, tracker_id)
Records what initiated the pause, and for how long the pause existed for.
This requires an external timer, and will be recorded when *Play* has been selected.
References DataLogger.intervention_level, DataLogger.paused_data, and DataLogger.start_timer().
record_errors()
record_errors (self, frame)
Not implemented
slider_moved()
slider_moved (self, frame_from, timer_id, tracker_id)
Records when the slider was changed, where from, and where to.
References DataLogger.intervention_level, DataLogger.slider_data, DataLogger.start_timer(), and DataLogger.timer_dict.
start_recording()
start_recording (self)
User input logging starts here #.
Starts the recording timer
References DataLogger.start_time_id, and DataLogger.timer_dict.
Referenced by DataLogger.start_timer().
start_timer()
start_timer (self, timer_id)
Starts the timer from when the project is initiated
References DataLogger.start_recording(), DataLogger.start_time_id, and DataLogger.timer_dict.
Referenced by DataLogger.adjustment(), DataLogger.paused(), and DataLogger.slider_moved().
The documentation for this class was generated from the following file:
K:/Github/PeopleTracker/src/datalogger.py