Peopletracker: PeopleTracker.src.maskrcnn Namespace Reference
PeopleTracker.src.maskrcnn Namespace Reference
Functions
load_predicted (pred_file)
display_preds (frame, frame_num, pred_dict, ratios)
predict (filename, model="mask_rcnn_coco_person.h5", class_names=["BG", "person"], step=10, display=False, progress=None, logger=None)
compute_iou (box, boxes, boxes_area, ratios=(1, 1), frame=None)
track_predictions (pred_dict, video, method=0, id_prefix="P", KalmanFilter=KalmanPred(), ratios=(1, 1), buffer=10, preview=True)
Variables
int NEAREST_CENTROID = 0
int NEAREST_CORNERS = 1
int NEAREST_BOX = 2
int NEAREST_KALMAN_CENTROID = 3
int NEAREST_KALMAN_CORNERS = 4
int NEAREST_KALMAN = 5
display
True
step
pred_dict = load_predicted("K:/Github/PeopleTracker/videos/(Simple) GP014125_predict.csv")
Detailed Description
Model from: https://github.com/Superlee506/Mask_RCNN_Humanpose
Cuda Version 10.1
CUDNN Version
                         # tensorflow==2.4.0 (Could be wrong??? just use GPU)d
Tensorflow version 2.3.0 # tensorflow-gpu==2.3.0
Function Documentation
compute_iou()
compute_iou (box, boxes, boxes_area, ratios = (1,1), frame = None)
Calculates IoU of the given box with the array of the given boxes.
box: 1D vector [x1, y1, x2, y2]
boxes: [boxes_count, (x1, y1, x2, y2)]
box_area: float. the area of 'box'
boxes_area: array of length boxes_count.
ratio: ratio (width, height) to scale boxes from video resolution to analysis resolution
Note: the areas are passed in rather than calculated here for
efficiency. Calculate once in the caller to avoid duplicate work.
References PeopleTracker.src.maskrcnn.load_predicted(), and PeopleTracker.src.maskrcnn.predict().
display_preds()
display_preds (frame, frame_num, pred_dict, ratios)
Displays the prediction
load_predicted()
load_predicted (pred_file)
Loads predicted data into a variable for later use.
Pred_dict[frame_number] = Lost of boxes
A box is described by:
x = box[0],
y = box[1],
width = box[2],
height = box[3]
Referenced by PeopleTracker.src.maskrcnn.compute_iou().
predict()
predict (filename, model = "mask_rcnn_coco_person.h5", class_names = ["BG", "person"], step = 10, display = False, progress = None, logger = None)
Uses MaskRCNN COCO models and uses them to predict items on the image.
Steps indicate how frequently the model should predict on the video (default every 10 frames)
Display shows predictions visually
Progress is a QProgressDialog for the application
Logger is a logger which both displays info and records it for crashlogger
Exports results into filename_predict.csv
Referenced by PeopleTracker.src.maskrcnn.compute_iou().