Peopletracker: PeopleTracker.src.utils Namespace Reference
PeopleTracker.src.utils Namespace Reference
Classes
class Dataset
Dataset.
Functions
extract_bboxes (mask)
Bounding Boxes.
compute_iou (box1, box2)
compute_overlaps_masks (masks1, masks2)
non_max_suppression (boxes, scores, threshold)
apply_box_deltas (boxes, deltas)
box_refinement_graph (box, gt_box)
box_refinement (box, gt_box)
resize_image (image, min_dim=None, max_dim=None, min_scale=None, mode="square")
resize_mask (mask, scale, padding, crop=None)
minimize_mask (bbox, mask, mini_shape)
expand_mask (bbox, mini_mask, image_shape)
mold_mask (mask, config)
unmold_mask (mask, bbox, image_shape)
generate_anchors (scales, ratios, shape, feature_stride, anchor_stride)
Anchors.
generate_pyramid_anchors (scales, ratios, feature_shapes, feature_strides, anchor_stride)
trim_zeros (x)
Miscellaneous.
compute_matches (gt_boxes, gt_class_ids, gt_masks, pred_boxes, pred_class_ids, pred_scores, pred_masks, iou_threshold=0.5, score_threshold=0.0)
compute_ap (gt_boxes, gt_class_ids, gt_masks, pred_boxes, pred_class_ids, pred_scores, pred_masks, iou_threshold=0.5)
compute_ap_range (gt_box, gt_class_id, gt_mask, pred_box, pred_class_id, pred_score, pred_mask, iou_thresholds=None, verbose=1)
compute_recall (pred_boxes, gt_boxes, iou)
batch_slice (inputs, graph_fn, batch_size, names=None)
download_trained_weights (coco_model_path, verbose=1)
norm_boxes (boxes, shape)
denorm_boxes (boxes, shape)
resize (image, output_shape, order=1, mode='constant', cval=0, clip=True, preserve_range=False, anti_aliasing=False, anti_aliasing_sigma=None)
distance_2d (p1, p2)
get_centroid (box)
get_corners (box)
Variables
str COCO_MODEL_URL = "https://github.com/matterport/Mask_RCNN/releases/download/v2.0/mask_rcnn_coco.h5"
Detailed Description
Mask R-CNN
Common utility functions and classes.
Copyright (c) 2017 Matterport, Inc.
Licensed under the MIT License (see LICENSE for details)
Written by Waleed Abdulla
Function Documentation
apply_box_deltas()
apply_box_deltas (boxes, deltas)
Applies the given deltas to the given boxes.
boxes: [N, (y1, x1, y2, x2)]. Note that (y2, x2) is outside the box.
deltas: [N, (dy, dx, log(dh), log(dw))]
batch_slice()
batch_slice (inputs, graph_fn, batch_size, names = None)
Splits inputs into slices and feeds each slice to a copy of the given
computation graph and then combines the results. It allows you to run a
graph on a batch of inputs even if the graph is written to support one
instance only.
inputs: list of tensors. All must have the same first dimension length
graph_fn: A function that returns a TF tensor that's part of a graph.
batch_size: number of slices to divide the data into.
names: If provided, assigns names to the resulting tensors.
box_refinement()
box_refinement (box, gt_box)
Compute refinement needed to transform box to gt_box.
box and gt_box are [N, (y1, x1, y2, x2)]. (y2, x2) is
assumed to be outside the box.
box_refinement_graph()
box_refinement_graph (box, gt_box)
Compute refinement needed to transform box to gt_box.
box and gt_box are [N, (y1, x1, y2, x2)]
compute_ap()
compute_ap (gt_boxes, gt_class_ids, gt_masks, pred_boxes, pred_class_ids, pred_scores, pred_masks, iou_threshold = 0.5)
Compute Average Precision at a set IoU threshold (default 0.5).
Returns:
mAP: Mean Average Precision
precisions: List of precisions at different class score thresholds.
recalls: List of recall values at different class score thresholds.
overlaps: [pred_boxes, gt_boxes] IoU overlaps.
References PeopleTracker.src.utils.compute_matches().
Referenced by PeopleTracker.src.utils.compute_ap_range().
compute_ap_range()
compute_ap_range (gt_box, gt_class_id, gt_mask, pred_box, pred_class_id, pred_score, pred_mask, iou_thresholds = None, verbose = 1)
Compute AP over a range or IoU thresholds. Default range is 0.5-0.95.
References PeopleTracker.src.utils.compute_ap().
compute_iou()
compute_iou (box1, box2)
Computes IOU of the two bounding boxes.
Referenced by PeopleTracker.src.utils.non_max_suppression().
compute_matches()
compute_matches (gt_boxes, gt_class_ids, gt_masks, pred_boxes, pred_class_ids, pred_scores, pred_masks, iou_threshold = 0.5, score_threshold = 0.0)
Finds matches between prediction and ground truth instances.
Returns:
    gt_match: 1-D array. For each GT box it has the index of the matched
              predicted box.
    pred_match: 1-D array. For each predicted box, it has the index of
                the matched ground truth box.
    overlaps: [pred_boxes, gt_boxes] IoU overlaps.
References PeopleTracker.src.utils.compute_overlaps_masks(), and PeopleTracker.src.utils.trim_zeros().
Referenced by PeopleTracker.src.utils.compute_ap().
compute_overlaps_masks()
compute_overlaps_masks (masks1, masks2)
Computes IoU overlaps between two sets of masks.
masks1, masks2: [Height, Width, instances]
Referenced by PeopleTracker.src.utils.compute_matches(), and PeopleTracker.src.utils.compute_recall().
compute_recall()
compute_recall (pred_boxes, gt_boxes, iou)
Compute the recall at the given IoU threshold. It's an indication
of how many GT boxes were found by the given prediction boxes.
pred_boxes: [N, (y1, x1, y2, x2)] in image coordinates
gt_boxes: [N, (y1, x1, y2, x2)] in image coordinates
References PeopleTracker.src.utils.compute_overlaps_masks().
denorm_boxes()
denorm_boxes (boxes, shape)
Converts boxes from normalized coordinates to pixel coordinates.
boxes: [N, (y1, x1, y2, x2)] in normalized coordinates
shape: [..., (height, width)] in pixels
Note: In pixel coordinates (y2, x2) is outside the box. But in normalized
coordinates it's inside the box.
Returns:
    [N, (y1, x1, y2, x2)] in pixel coordinates
download_trained_weights()
download_trained_weights (coco_model_path, verbose = 1)
Download COCO trained weights from Releases.
coco_model_path: local path of COCO trained weights
expand_mask()
expand_mask (bbox, mini_mask, image_shape)
Resizes mini masks back to image size. Reverses the change
of minimize_mask().
See inspect_data.ipynb notebook for more details.
References PeopleTracker.src.utils.resize().
extract_bboxes()
extract_bboxes (mask)
Bounding Boxes.
Compute bounding boxes from masks.
mask: [height, width, num_instances]. Mask pixels are either 1 or 0.
Returns: bbox array [num_instances, (y1, x1, y2, x2)].
generate_anchors()
generate_anchors (scales, ratios, shape, feature_stride, anchor_stride)
Anchors.
scales: 1D array of anchor sizes in pixels. Example: [32, 64, 128]
ratios: 1D array of anchor ratios of width/height. Example: [0.5, 1, 2]
shape: [height, width] spatial shape of the feature map over which
        to generate anchors.
feature_stride: Stride of the feature map relative to the image in pixels.
anchor_stride: Stride of anchors on the feature map. For example, if the
    value is 2 then generate anchors for every other feature map pixel.
Referenced by PeopleTracker.src.utils.generate_pyramid_anchors().
generate_pyramid_anchors()
generate_pyramid_anchors (scales, ratios, feature_shapes, feature_strides, anchor_stride)
Generate anchors at different levels of a feature pyramid. Each scale
is associated with a level of the pyramid, but each ratio is used in
all levels of the pyramid.
Returns:
anchors: [N, (y1, x1, y2, x2)]. All generated anchors in one array. Sorted
    with the same order of the given scales. So, anchors of scale[0] come
    first, then anchors of scale[1], and so on.
References PeopleTracker.src.utils.generate_anchors().
get_centroid()
get_centroid (box)
returns centroid of a box, given the box is in format (x1, y1, x2, y2)
get_corners()
get_corners (box)
returns 2 point pairs describing the corners of the box
minimize_mask()
minimize_mask (bbox, mask, mini_shape)
Resize masks to a smaller version to reduce memory load.
Mini-masks can be resized back to image scale using expand_masks()
See inspect_data.ipynb notebook for more details.
References PeopleTracker.src.utils.resize().
non_max_suppression()
non_max_suppression (boxes, scores, threshold)
Performs non-maximum suppression and returns indices of kept boxes.
boxes: [N, (y1, x1, y2, x2)]. Notice that (y2, x2) lays outside the box.
scores: 1-D array of box scores.
threshold: Float. IoU threshold to use for filtering.
References PeopleTracker.src.utils.compute_iou().
norm_boxes()
norm_boxes (boxes, shape)
Converts boxes from pixel coordinates to normalized coordinates.
boxes: [N, (y1, x1, y2, x2)] in pixel coordinates
shape: [..., (height, width)] in pixels
Note: In pixel coordinates (y2, x2) is outside the box. But in normalized
coordinates it's inside the box.
Returns:
    [N, (y1, x1, y2, x2)] in normalized coordinates
resize()
resize (image, output_shape, order = 1, mode = 'constant', cval = 0, clip = True, preserve_range = False, anti_aliasing = False, anti_aliasing_sigma = None)
A wrapper for Scikit-Image resize().
Scikit-Image generates warnings on every call to resize() if it doesn't
receive the right parameters. The right parameters depend on the version
of skimage. This solves the problem by using different parameters per
version. And it provides a central place to control resizing defaults.
Referenced by PeopleTracker.src.utils.expand_mask(), PeopleTracker.src.utils.minimize_mask(), and PeopleTracker.src.utils.resize_image().
resize_image()
resize_image (image, min_dim = None, max_dim = None, min_scale = None, mode = "square")
Resizes an image keeping the aspect ratio unchanged.
min_dim: if provided, resizes the image such that it's smaller
    dimension == min_dim
max_dim: if provided, ensures that the image longest side doesn't
    exceed this value.
min_scale: if provided, ensure that the image is scaled up by at least
    this percent even if min_dim doesn't require it.
mode: Resizing mode.
    none: No resizing. Return the image unchanged.
    square: Resize and pad with zeros to get a square image
        of size [max_dim, max_dim].
    pad64: Pads width and height with zeros to make them multiples of 64.
           If min_dim or min_scale are provided, it scales the image up
           before padding. max_dim is ignored in this mode.
           The multiple of 64 is needed to ensure smooth scaling of feature
           maps up and down the 6 levels of the FPN pyramid (2**6=64).
    crop: Picks random crops from the image. First, scales the image based
          on min_dim and min_scale, then picks a random crop of
          size min_dim x min_dim. Can be used in training only.
          max_dim is not used in this mode.
Returns:
image: the resized image
window: (y1, x1, y2, x2). If max_dim is provided, padding might
    be inserted in the returned image. If so, this window is the
    coordinates of the image part of the full image (excluding
    the padding). The x2, y2 pixels are not included.
scale: The scale factor used to resize the image
padding: Padding added to the image [(top, bottom), (left, right), (0, 0)]
References PeopleTracker.src.utils.resize().
resize_mask()
resize_mask (mask, scale, padding, crop = None)
Resizes a mask using the given scale and padding.
Typically, you get the scale and padding from resize_image() to
ensure both, the image and the mask, are resized consistently.
scale: mask scaling factor
padding: Padding to add to the mask in the form
        [(top, bottom), (left, right), (0, 0)]
trim_zeros()
trim_zeros (x)
Miscellaneous.
It's common to have tensors larger than the available data and
pad with zeros. This function removes rows that are all zeros.
x: [rows, columns].
Referenced by PeopleTracker.src.utils.compute_matches().
unmold_mask()
unmold_mask (mask, bbox, image_shape)
Converts a mask generated by the neural network to a format similar
to its original shape.
mask: [height, width] of type float. A small, typically 28x28 mask.
bbox: [y1, x1, y2, x2]. The box to fit the mask in.
Returns a binary mask with the same size as the original image.